# Generated by Django 5.2.7 on 2026-01-26 16:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarOverride',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False, unique=True, verbose_name='Data')),
                ('day_type', models.CharField(choices=[('Working', 'Dzień roboczy'), ('Free', 'Dzień wolny')], max_length=20, verbose_name='Typ dnia')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notatka')),
            ],
            options={
                'verbose_name': 'Override kalendarza',
                'verbose_name_plural': "Override'y kalendarza",
                'db_table': 'calendar_override',
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Hasło (hash)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('daily_norm_minutes', models.PositiveIntegerField(default=480, verbose_name='Dzienna norma czasu (minuty)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
                'db_table': 'employee',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='TaskCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True, verbose_name='ID zewnętrzne')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktywny')),
                ('display_name', models.CharField(max_length=255, verbose_name='Nazwa wyświetlana')),
                ('search_text', models.TextField(verbose_name='Tekst do wyszukiwania')),
                ('account', models.CharField(blank=True, max_length=255, null=True, verbose_name='Konto')),
                ('project', models.CharField(blank=True, max_length=255, null=True, verbose_name='Projekt')),
                ('phase', models.CharField(blank=True, max_length=255, null=True, verbose_name='Faza')),
                ('project_phase', models.CharField(blank=True, max_length=255, null=True, verbose_name='Projekt - Faza')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Departament')),
                ('discipline', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dyscyplina')),
                ('task_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Typ zadania')),
                ('fields_json', models.JSONField(blank=True, null=True, verbose_name='Pola JSON (rezerwowe)')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Ostatnia synchronizacja')),
            ],
            options={
                'verbose_name': 'Zadanie (cache)',
                'verbose_name_plural': 'Zadania (cache)',
                'db_table': 'task_cache',
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['is_active'], name='idx_task_is_active'), models.Index(fields=['external_id'], name='idx_task_external_id')],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='Data pracy')),
                ('duration_minutes_raw', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Czas trwania (minuty)')),
                ('billable_half_hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rozliczalne półgodziny')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='timetracker_app.employee', verbose_name='Pracownik')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='timetracker_app.taskcache', verbose_name='Zadanie')),
            ],
            options={
                'verbose_name': 'Wpis czasu',
                'verbose_name_plural': 'Wpisy czasu',
                'db_table': 'time_entry',
                'ordering': ['-work_date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'work_date'], name='idx_entry_emp_date'), models.Index(fields=['work_date'], name='idx_entry_date')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'work_date', 'task'), name='unique_entry_per_employee_date_task'), models.CheckConstraint(condition=models.Q(('duration_minutes_raw__gt', 0)), name='check_duration_positive'), models.CheckConstraint(condition=models.Q(('billable_half_hours__gte', 1)), name='check_billable_min_one')],
            },
        ),
    ]
