# Generated by Django 5.2.7 on 2026-01-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker_app', '0002_add_auth_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=100, verbose_name='Typ jobu')),
                ('dedup_key', models.CharField(max_length=255, unique=True, verbose_name='Klucz deduplikacji')),
                ('payload_json', models.JSONField(verbose_name='Payload JSON')),
                ('status', models.CharField(choices=[('PENDING', 'Oczekujące'), ('RUNNING', 'W trakcie'), ('DONE', 'Zakończone'), ('FAILED', 'Nieudane')], default='PENDING', max_length=20, verbose_name='Status')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Liczba prób')),
                ('run_after', models.DateTimeField(verbose_name='Uruchom po')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='Ostatni błąd')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Job outbox',
                'verbose_name_plural': 'Joby outbox',
                'db_table': 'outbox_job',
                'ordering': ['run_after'],
                'indexes': [models.Index(fields=['status', 'run_after'], name='idx_outbox_status_run'), models.Index(fields=['dedup_key'], name='idx_outbox_dedup'), models.Index(fields=['job_type'], name='idx_outbox_job_type')],
            },
        ),
    ]
