# Generated by Django 5.2.7 on 2026-01-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker_app', '0003_outboxjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcache',
            name='account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='taskcache',
            name='discipline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Branża'),
        ),
    ]
